# Database Tasks for Cardinal Project
# Specialized tasks for database operations, migrations, and management

version: '3'

tasks:
  # Database Connection Tasks
  db:status:
    desc: Check database connection status
    cmds:
      - echo "Checking database connection status..."
      - npm run db:test
    sources:
      - database/test-connection.js
      - database/supabase.ts

  db:info:
    desc: Show database information
    cmds:
      - echo "Database Information"
      - echo "Project Cardinal Travel Itinerary Generator"
      - echo "Database Supabase/PostgreSQL"
      - echo "Available migrations"
      - ls -la database/migrations/
      - echo "Database scripts"
      - ls -la database/

  # Database Migration Tasks
  db:migrate:status:
    desc: Show migration status
    cmds:
      - echo "Migration Status"
      - echo "This will show which migrations have been applied"
      - echo "Run task db:deploy to see current status"

  db:migrate:create:
    desc: Create a new migration file
    cmds:
      - echo "Creating new migration file"
      - echo "Usage task db:migrate:create migration_description"

  db:migrate:rollback:
    desc: Rollback last migration (manual process)
    cmds:
      - echo "Manual rollback process"
      - echo "1. Check database/migrations/ for the last applied migration"
      - echo "2. Manually execute the rollback SQL in your database"
      - echo "3. Update your migration tracking if applicable"

  # Database Schema Tasks
  db:schema:show:
    desc: Show current database schema
    cmds:
      - echo "Current Database Schema"
      - echo "Tables"
      - echo "- profiles (user profiles)"
      - echo "- travel_requirements (user travel preferences)"
      - echo "- itineraries (generated travel plans)"
      - echo "Run task db:deploy to apply latest schema changes"

  db:schema:validate:
    desc: Validate database schema
    cmds:
      - echo "Validating database schema"
      - npm run db:deploy
      - npm run db:test
      - echo "Schema validation completed"

  # Database Development Tasks
  db:dev:reset:
    desc: Reset development database (DESTRUCTIVE)
    cmds:
      - echo "WARNING This will reset your development database"
      - echo "This action cannot be undone"
      - echo "Run npm run db:deploy:dev to reset"

  db:dev:seed:
    desc: Seed development database with sample data
    cmds:
      - echo "Seeding development database"
      - echo "This will add sample travel requirements and itineraries"
      - echo "Run task db:deploy:dev first to ensure schema is up to date"

  # Database Backup and Restore
  db:backup:create:
    desc: Create database backup (if supported by your setup)
    cmds:
      - echo "Database backup functionality"
      - echo "For Supabase backups are typically handled automatically"
      - echo "Check your Supabase dashboard for backup options"

  db:backup:restore:
    desc: Restore database from backup (if supported by your setup)
    cmds:
      - echo "Database restore functionality"
      - echo "For Supabase restores are typically handled through the dashboard"

  # Database Performance Tasks
  db:performance:analyze:
    desc: Analyze database performance
    cmds:
      - echo "Database Performance Analysis"
      - echo "This would typically involve"
      - echo "1. Query performance analysis"
      - echo "2. Index optimization"
      - echo "3. Connection pooling review"
      - echo "Consider using Supabase built-in performance monitoring"

  # Database Security Tasks
  db:security:audit:
    desc: Audit database security
    cmds:
      - echo "Database Security Audit"
      - echo "1. Check RLS (Row Level Security) policies"
      - echo "2. Verify API key permissions"
      - echo "3. Review user access controls"
      - echo "4. Check for sensitive data exposure"
      - echo "Run task security:audit for general security checks"

  # Database Monitoring Tasks
  db:monitor:setup:
    desc: Setup database monitoring
    cmds:
      - echo "Database Monitoring Setup"
      - echo "Supabase provides built-in monitoring"
      - echo "- Query performance"
      - echo "- Connection usage"
      - echo "- Storage usage"
      - echo "- API usage"
      - echo "Check your Supabase dashboard for monitoring options"

  # Database Health Check
  db:health:
    desc: Comprehensive database health check
    deps: [db:status, db:schema:validate, db:security:audit]
    cmds:
      - echo "Database health check completed"
      - echo "All systems are operational"
