[build]
  # Build settings
  publish = "."
  functions = "netlify/functions"

[build.environment]
  # Python version for functions
  PYTHON_VERSION = "3.9"

[[redirects]]
  # Redirect API calls to the function
  from = "/api/discover"
  to = "/.netlify/functions/discover"
  status = 200

[[redirects]]
  # Serve the main HTML file for the root path
  from = "/"
  to = "/index.html"
  status = 200

[functions]
  # Function settings
  directory = "netlify/functions"