[build]
  # Build command for Next.js
  command = "npm run build"
  
  # Output directory for Next.js static export
  publish = "out"
  
  # Functions directory for Netlify Functions
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Enable Next.js telemetry (optional)
  NEXT_TELEMETRY_DISABLED = "1"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["visitor"]}

# API routes redirect to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self)"
    
    # Content Security Policy (will need adjustment as features are added)
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self' https://api.anthropic.com https://maps.googleapis.com; frame-ancestors 'none';"

# Cache headers for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Edge functions configuration (for the main concierge agent)
[[edge_functions]]
  function = "concierge"
  path = "/api/concierge"

# Function-specific configurations
[functions]
  # Default timeout for standard functions
  timeout = 60
  
  # Environment variables prefix
  node_bundler = "esbuild"

# Plugin configurations
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Development settings
[dev]
  command = "npm run dev"
  port = 3000
  publish = "out"
  functions = "netlify/functions"